정근님 OAuth 발표 리뷰
chocolate-factory/chocolatier-meetup pull request #4
Opened 2018-04-16 02:50 UTC by yangroro

2018-04-16 06:00 UTC, demarlik01 commented
커밋 정리좀요ㅡㅡ

2018-04-22 03:28 UTC, yangroro commented
@JungleKim 커밋 정리 해주세요.

2018-04-23 02:58 UTC, JungleKim commented
뭘 어떻게 정리해달란 말인가요?

2018-04-23 03:00 UTC, yangroro commented
커밋 좀 합쳐주세요.

2018-04-23 03:01 UTC, incleaf commented
@demarlik01 @yangroro 보통 커밋은 머지할 때 정리하지 않습니까?

2018-04-23 03:03 UTC, JungleKim commented
Sqush Merge Require로 하시죠

2018-04-23 03:04 UTC, JungleKim commented
개인적으로 뭐가 문젠지는 모르겠지만.. 굳이 정리하자면 그냥 스쿼시로 전부 일괄적으로 정리하면 될것같네요

2018-04-23 06:00 UTC, incleaf requested changes

2018-04-23 06:00 UTC, incleaf commented on OAuth/README.md
> +#스터디/oauth2
제거가 필요합니다아

2018-04-23 06:00 UTC, incleaf commented on OAuth/README.md
> +-> 인증 서버
`->` 이건 의도된 건가요?

2018-04-23 06:00 UTC, incleaf commented on OAuth/README.md
> +## 코멘트
코멘트도 이 PR 정도에만 남겨두고 없애는 건 어떨까요?

2018-04-23 07:54 UTC, JungleKim commented on OAuth/README.md
> +-> 인증 서버
강조정도였는데 Markdown문법으로 교체해놓겠습니다.

2018-04-23 13:08 UTC, ianchobuilds requested changes
발표를 못 들어서 아쉽네요 😭

2018-04-23 13:08 UTC, gyujincho commented on OAuth/README.md
> +하지만, OpenID의 목적은 로그인 OAuth의 목적은 권한허가라는 점에서 차이점이 있습니다.
@JungleKim `하지만 OpenID의 목적은 로그인**,** OAuth의 목적은 권한허가라는 점에서 차이점이 있습니다.`로 마침표 위치를 변경하는 게 좋을 것 같아요~

2018-04-23 13:08 UTC, gyujincho commented on OAuth/README.md
> +`OAuth 2.0`의 설명에 앞서 몇가지 Role을 알아야합니다.
@JungleKim  불필요한 문장인 것 같습니다.

2018-04-24 10:05 UTC, JungleKim commented
@incleaf @gyujincho 말씀해주신 피드백 반영했습니다.

2018-04-24 10:06 UTC, ianchobuilds approved these changes

2018-04-24 16:44 UTC, Junu-Sinclair requested changes
코멘트들 외에

요소들 설명을 제외하고 내용을 설명하는 부분에서는

~한다 / ~합니다
둘 중 하나로 통합하는게 추가되면 더 좋을 것 같아요~

2018-04-24 16:44 UTC, JunuSinclair commented on OAuth/README.md
> +이렇게 파편화된 인증방식들을 통합한 표준이라고 할 수 있습니다.
`OAuth`이전에 기존의 각 회사들이 인증방식을 직접 구현해서 사용했고,
이 파편화된 인증방식들을 통합한 표준이 `OAuth`라고 할 수 있습니다.

정도로 정리하면 더 잘 읽히지 않을까요?

2018-04-24 16:44 UTC, JunuSinclair commented on OAuth/README.md
> +하지만 OpenID의 목적은 로그인, OAuth의 목적은 권한허가라는 점에서 차이점이 있습니다.
권한허가라는 차이점이 있습니다.

로만 써도 충분할 것 같습니다.

2018-04-24 16:44 UTC, JunuSinclair commented on OAuth/README.md
> +자주 사용되지는 않지만 2-legged 방식도 `OAuth 2.0`에 포함됩니다.
자주 -> 또, 자주

로 이어지는 내용임을 명시하는건 어떨까요?

2018-04-24 16:44 UTC, JunuSinclair commented on OAuth/README.md
> +인증 서버에 2개와 클라이언트에서 1개를 사용합니다.
`OAuth 2.0`가 인증 과정중에 사용하는 Endpoint는
인증 서버에 2개와 클라이언트에서 1개로 총 3개를 사용합니다.

정도로 정리하면 더 잘 읽힐 것 같습니다

2018-04-26 03:45 UTC, incleaf approved these changes

2018-05-06 06:18 UTC, yangroro commented
approve

2018-05-08 00:50 UTC, Junu-Sinclair approved these changes

2018-05-08 02:03 UTC, merged