준우님 Asynchronous javascript 발표 리뷰
chocolate-factory/chocolatier-meetup pull request #5
Opened 2018-04-16 02:50 UTC by yangroro

2018-04-16 02:52 UTC, yangroro commented
이건 머지하고 /README.md 수정을 좀 해줘야겠네요.

2018-04-16 02:53 UTC, incleaf commented
@JunuSinclair 우선 `Javascript` -> `JavaScript`로 수정이 필요합니다 ㅋㅋ

2018-04-23 05:31 UTC, JungleKim requested changes

2018-04-23 05:31 UTC, JungleKim commented on Asynchronous javascript/README.md
> +위의 코드에서  funcA(); funcB(); 의 순서대로 코드를 실행하면 결과는
```javascript
funcA();
funcB();
```

함수 실행부분을 명시적으로 위 코드블럭에 포함시키는게 좋을 것 같습니다.
그리고 `위 코드를 실행하면 결과는 아래와 같다.` 이런 느낌으로 수정하는게 더 깔끔할것 같습니다.

2018-04-23 05:31 UTC, JungleKim commented on Asynchronous javascript/README.md
> +```
\`\`\` -> \`\`\`javascript

2018-04-23 05:31 UTC, JungleKim commented on Asynchronous javascript/README.md
> +```
\`\`\` -> \`\`\`javascript

2018-04-23 05:31 UTC, JungleKim commented on Asynchronous javascript/README.md
> +```
\`\`\` -> \`\`\`javascript

코드블럭들에 일괄적용 부탁드립니다.

2018-04-23 05:31 UTC, JungleKim commented on Asynchronous javascript/README.md
> +*위 코드는 MDN 에서 Event Loop 를 설명하는 가상 코드다.*
마크다운을 `\*문장문장\*` 보다 `\> 문장문장`으로 하는게 보기에 좋을 것 같습니다.
머리로 상상해본거라서 수정해보고 영 아니면 그대로 두셔도 무방합니다.

2018-04-23 05:31 UTC, JungleKim commented on Asynchronous javascript/README.md
> +**Timer 의 setTimeout 요청**
여기 실제로 보면 한줄로 보입니다.
개행을 하려면 줄의 맨끝에 space 두번 넣어주세요.

2018-04-23 05:31 UTC, JungleKim commented on Asynchronous javascript/README.md
> +::만약 setTimeout 에 지정된 Interval 이 0ms 일 경우에는 Timer 에서 대기하는 3번의 과정만 0ms 혹은 브라우저 최소 대기 시간일 뿐이지 메서드가 실행된 후 다음순번으로 대기중이던 호출 스택 요소가 모두 종료 된 후에 실행되게 된다.::
:: 같은경우 마크다운 문법으로 존재하지 않아서 다른 문법으로 변경하는 게 좋아보입니다.
Preview로 확인해보니 ::가 없어도 이상할 것 같진 않아서 아에 제거하는것도 좋아보이네요.

2018-04-23 05:35 UTC, incleaf commented
@JunuSinclair 괄호 전후의 띄어쓰기가 모두 제거되어야 할 것 같습니다.

2018-04-23 05:38 UTC, incleaf requested changes

2018-04-23 05:38 UTC, incleaf commented on Asynchronous javascript/README.md
> +## Javascript Engine 내의 호출 스택 ( Call stack )
괄호 전후의 띄어쓰기가 제거되어야 할 것 같습니다.

2018-04-23 05:38 UTC, incleaf commented on Asynchronous javascript/README.md
> + 또 Stack 의 기본 구조를 따르기 때문에 함수를 Push ( 추가 ) 하고 실행시에 Pop ( 제거 ) 하는 순으로 진행되며 그 사이에는 다른 함수로 인한 Interrupt 가 발생할 수 없는 구조이다. ( *Run-to-completion :  각 작업이 당시 모든 상태를 간섭의 우려 없이 완벽하게 제어 할 수 있다는 걸 의미. )
괄호 전후의 띄어쓰기가 제거되어야 할 것 같습니다. Run-to-completion 같은 부연 설명은 각주를 만들어 두는 게 어떨까요?

2018-04-23 05:38 UTC, incleaf commented on Asynchronous javascript/README.md
> +* **setTimeout** : 지정된 시간 이후 콜백을 한번 실행
콜론 이전 스페이스 제거 필요합니다.

2018-04-23 05:38 UTC, incleaf commented on Asynchronous javascript/README.md
> +* **setInterval** :  지정된 시간 간격으로 콜백을 실행
콜론 이전 스페이스 제거 필요합니다.

2018-04-23 05:38 UTC, incleaf commented on Asynchronous javascript/README.md
> + Callback 을 이용하면서 CPS 의 스타일을 사용하게 되면서 장점도 분명히 존재하지만 코드 복잡도가 상승하면서 직관성이 떨어지는 단점이 존재한다. ( a.k.a callback 지옥 )
괄호 전후의 띄어쓰기가 제거되어야 할 것 같습니다. `a.k.a` -> `a.k.a.`

2018-04-23 05:38 UTC, incleaf commented on Asynchronous javascript/README.md
> + 보통 일반적으로는 입력 ( 매개변수 ) 와 출력 ( 결과 ) 사이의 구분이 명확하지만, Callback 을 사용하는 비동기 함수는 이 구분이 모호하기 때문에 복잡도는 계속 상승한다. ( factorial 을 CPS 를 이용하여 구현하는 등... )
괄호 전후의 띄어쓰기가 제거되어야 할 것 같습니다.

2018-04-23 05:41 UTC, incleaf commented on Asynchronous javascript/README.md
> +# Asynchronous javascript
`javascript` -> `JavaScript`

2018-04-23 05:41 UTC, incleaf commented on Asynchronous javascript/README.md
> + 일반적으로 C, Java 와 같은 언어는 별도의 Thread 등을 사용하지 않는 이상은 위에서 아래로 흐름에 따라 절차적으로 진행되는 언어와는 다른 특성을 지니지만 Javascript 는 특정 명령이 실행 되고나서 명령이 완료되기 전에 다음 명령이 실행될 가능성이 다분하다.
`javascript` -> `JavaScript`

2018-04-23 05:48 UTC, incleaf commented
## 글에서 공통적으로 수정되어야 할 부분

1. 기술명 대소문자
예) `javascript` -> `JavaScript`

2. 문장부호 문법 수정
- 괄호 공백 제거: `( 매개변수 )` -> `(매개변수)`

3. 영어 단어 후 띄어쓰기 수정
해당 부분은 관련된 문법이 있는지 잘 모르겠으나 이 방식이 더 자연스럽게 느껴지는데 어떻게 생각하시나요?
예) `JavaScript 는` -> `JavaScript는`

## 질문 
`::Example::` 이처럼 특정 내용을 쌍점 두 개로 감싸는 건 혹시 레퍼런스가 있는건가요?

2018-04-23 05:53 UTC, JunuSinclair commented
@incleaf ::내용:: bear 에서 하이라이트 처리할때 쓰던건데 export 하면서 그대로 내려온거 같네요

2018-04-23 13:20 UTC, ianchobuilds requested changes
@incleaf @yangroro @JunuSinclair @JungleKim 
리뷰 내용에서 띄어쓰기 등 문법적인 부분은 최소화할 수 있도록 각자 PR 전에 맞춤법 검사기를 한 번 돌리는 건 어떨까요?

2018-04-23 13:20 UTC, ianchobuilds commented on Asynchronous javascript/README.md
> + Promises는 비동기 프로그래밍의 한 부분을 도와주는 패턴 이며, 함수 또는 메서드를 비동기적으로 결과를 받게 된다.
@JunuSinclair 'Promises는 비동기 프로그래밍의 한 부분을 도와주는 패턴이며, 함수 또는 메서드에서 비동기적으로 비동기 코드의 실행 결과를 받게 된다.` 전달하고자 하는 바가 정확히 이것인지는 모르겠지만 이런 방식으로 수정되면 더 좋을 것 같습니다~

2018-04-23 13:20 UTC, ianchobuilds commented on Asynchronous javascript/README.md
> +es6 이전의 jQuery 가 주로 사용되던 때에는 deferred 를 이용하여 패턴을 사용했었다.
@JunuSinclair `deffered`와 `Promises`의 차이 혹은 공통점을 아래의 코드뿐 아니라 문장으로도 설명하면 더 좋을 것 같아요.

2018-04-23 13:20 UTC, ianchobuilds commented on Asynchronous javascript/README.md
> +![code flow process_2](2.png)
@JunuSinclair [제안] 화살표 스타일을 조금 더 알아보기 쉬운 쪽으로 변경하면 어떨까요?

2018-04-26 01:53 UTC, JunuSinclair commented on Asynchronous javascript/README.md
> +![code flow process_2](2.png)
엌ㅋㅋㅋㅋ 이건 이미지를 수정해야해서 일단 고려해보겠습니닼ㅋㅋㅋ 의견 감사합니다

2018-04-26 03:12 UTC, JunuSinclair commented on Asynchronous javascript/README.md
> +es6 이전의 jQuery 가 주로 사용되던 때에는 deferred 를 이용하여 패턴을 사용했었다.
이건 제가 조금 더 찾아보고 추가 보충 하는걸로 할게요~!

2018-04-26 03:26 UTC, JunuSinclair commented
@incleaf @JungleKim @yangroro @gyujincho 
따로 코멘트 단것 외에는 수정 했습니다.

코멘트 단 것들은 추후 업데이트 하는걸로 진행 할게요!

2018-05-04 16:41 UTC, JungleKim approved these changes

2018-05-06 06:18 UTC, yangroro commented
이거 PR을 제가 열어서 저는 리뷰를 할 수가 없네요. 전 approve합니당.

2018-05-26 04:12 UTC, merged