Docker 자료 리뷰
chocolate-factory/chocolatier-meetup pull request #6
Opened 2018-04-22 05:15 UTC by yangroro

2018-04-23 02:59 UTC, JungleKim approved these changes

2018-04-23 05:18 UTC, JungleKim requested changes

2018-04-23 05:18 UTC, JungleKim commented on docker/README.md
> +[참고자료](https://github.com/chocolate-factory/docker-compose-example)
이 부분은 조금 더 강조해주는 것은 어떨까요?
내용상 단순한 참고자료이상의 역할을 하는 것 같습니다.
글을 온전히 이해하려면 반드시 같이 봐야 한다는 생각이 듭니다.

2018-04-23 05:18 UTC, JungleKim commented on docker/README.md
> +[참고자료](https://github.com/chocolate-factory/docker-compose-example)
아니면 참고자료의 일부를 해당 문서에 포함시키는 것도 방법일 것 같네요.

2018-04-23 05:19 UTC, yangroro commented on docker/README.md
> +[참고자료](https://github.com/chocolate-factory/docker-compose-example)
보충을 좀 해야겠네요.

2018-04-23 05:44 UTC, JungleKim commented on docker/README.md
> +[참고자료](https://github.com/chocolate-factory/docker-compose-example)
보충할 내용에 docker/docker-compose를 사용하기전 brew를 이용해서 redis와 node등등을 띄울때와 비교해서 보여주면 좀 더 극적인 효과를 볼 수 있을 것 같습니다.

2018-04-23 12:59 UTC, ianchobuilds requested changes

2018-04-23 12:59 UTC, gyujincho commented on docker/README.md
> +Virtual Machine과 차별화 되는 점이 가상화를 하는 과정에서 발생하는 OverHead가 없습니다.
@yangroro 주어 동사 호응을 맞추기 위해 '가상화를 하는 과정에서 발생하는 OverHead가 없다는 점에서 Virtual Machine과 차별화되었습니다.' 로 변경하면 어떨까요?

2018-04-23 12:59 UTC, gyujincho commented on docker/README.md
> +Virtual Machine과 차별화 되는 점이 가상화를 하는 과정에서 발생하는 OverHead가 없습니다.
@yangroro 발표 당시 질문이 나왔던 '가상 머신에서의 `OverHead`는 무엇이며 Docker에선 왜 없는지'에 대한 설명도 추가되면 좋을 것 같습니다.

2018-04-24 16:47 UTC, Junu-Sinclair approved these changes
발표시에 중간중간 참고했었던 코드만 같이 참고되면 좋을 것 같습니다.

다른분들이 남겨주신 리뷰 외에 따로 코멘트할 건 없는것 같아요~

2018-05-09 08:54 UTC, incleaf approved these changes

2018-05-20 06:44 UTC, yangroro commented
아예 제가 블로그에 쓴 글을 옮겼습니다.

2018-05-26 03:14 UTC, merged