문서 작성 가이드 추가
chocolate-factory/chocolatier-meetup pull request #7
Opened 2018-04-24 10:19 UTC by JungleKim

문서 작성 / 업로드 룰을 작성했습니다.

추가되었으면 하는 룰이 있으면 코멘트로 달아주세요.

2018-04-24 10:22 UTC, ianchobuilds commented on README.md
> +- 문서의 내용 중 별도의 설명이 필요한 경우 각주를 이용한다.
@JungleKim 각주를 어떤 형식으로 달아야 하나요?

2018-04-24 10:31 UTC, JungleKim commented on README.md
> +- 문서의 내용 중 별도의 설명이 필요한 경우 각주를 이용한다.
아... Github Markdown에는 각주 기능이 없네요 :(

2018-04-24 10:35 UTC, JungleKim commented
보통 마크다운은 각주를 위해 아래 문법을 지원하는데, Github에는 이 기능이 없네요.
Snippets를 제공하던지 아니면.. 
각주관련 룰을 제거하던지... 
또 아니면 Blog를 빠르게 구축해서 각주를 사용할 수 있게 하던지... 
선택을 해야할것 같네요.

Snippets을 제공한다면 <sup> 태그를 직접 md에 입력해야합니다.

```
각주는 대체로 레퍼런스의 링크를 나타내기 위해 사용합니다.[^1]

[^1]: 이게 바로 각주입니다.
```

2018-04-24 16:01 UTC, incleaf commented
@JungleKim 저는 각주를 정근님이 작성해주신 https://github.com/chocolate-factory/chocolatier-meetup/pull/7#issuecomment-383884899 처럼 작성하는 것을 생각했습니다.

2018-04-24 16:12 UTC, incleaf requested changes

2018-04-24 16:12 UTC, incleaf commented on README.md
> +## 문서 업로드 규칙
`문서 작성 규칙`은 어떨까요?

2018-04-24 16:12 UTC, incleaf commented on README.md
> +- PR을 올리기 전 맞춤법 검사기를 통해 맞춤법과 문법을 올바르게 고친다.
다음은 어떤가요?
> 문서 작성 후 리뷰를 요청하기 전에 맞춤법 검사기를 사용하여 글을 가다듬는다.

2018-04-24 16:12 UTC, incleaf commented on README.md
> +    - 기본적인 맞춤법과 문법을 배제한 리뷰를 하기 위함.
이는 제거해도 좋을 것 같습니다.

2018-04-24 16:12 UTC, incleaf commented on README.md
> +- 문서를 업로드할 때 포맷은 Github Markdown으로 한다.
다음은 어떤가요?
> 문서는 [Markdown](https://en.wikipedia.org/wiki/Markdown) 문법을 사용하여 작성하며 GitHub에서 이상 없이 보이는 것을 기준으로 한다.

2018-04-24 16:12 UTC, incleaf commented on README.md
> +- 문서를 작성할 때 참고한 링크들은 최하단에 일괄적으로 작성한다.
`링크`를 `문서`로 바꾸는 것이 좋을 것 같습니다.

2018-04-24 16:12 UTC, incleaf commented on README.md
> +- 문서의 내용 중 등장하는 단어에 문서와 상관없는 별도의 설명이 필요한 경우 각주를 이용한다.
이걸 규칙으로써 강제할 필요는 없을 것 같은데 어떻게 생각하시나요?

2018-04-25 05:55 UTC, JungleKim commented
@incleaf 흠.. 보여주신 형태도 결국 Markdown에서 쓰려면 html tag로 써야할것 같습니다.

2018-04-25 05:59 UTC, JungleKim commented on README.md
> +- 문서의 내용 중 등장하는 단어에 문서와 상관없는 별도의 설명이 필요한 경우 각주를 이용한다.
음.. 이름이 규칙이라 강제성을 띄는 느낌이드는데, 
사실 의도한 건 글쓴이가 판단해서 글에 방해가 되면 각주로 빼자 정도 였습니다.

2018-04-25 05:59 UTC, incleaf commented
@JungleKim 보여주신 형태라는게 정근님이 작성하신 코멘트를 말씀하시는 건가요?

2018-04-25 06:00 UTC, JungleKim commented on README.md
> +## 문서 업로드 규칙
규칙보다 가이드가 더 좋을 것 같네요. 강제성을 띄지않는 단순 가이드들도 포함할 예정이라..

2018-04-25 06:02 UTC, JungleKim commented
@incleaf 아뇨 https://github.com/chocolate-factory/chocolatier-meetup/pull/7#issuecomment-383884899 이 부분 말하는 겁니당

2018-04-25 06:03 UTC, incleaf commented
@JungleKim 그 코멘트가 정근님이 작성하신 코멘트인데요..?

2018-04-25 07:01 UTC, JungleKim commented
@incleaf 링크하는 형태를 설명하는줄 알았습니다 ㅋㅋㅋ

그럼 여러가지 방안중에 결정하면 되겠네요.

2018-04-25 07:08 UTC, incleaf commented
```
리액트[^1]와 리덕스[^2]를 사용하여 재사용하기 좋은 컴포넌트를 쉽게 구성할 수 있다.

[^1]: 페이스북에서 운영하는 프론트엔드 오픈 소스 프로젝트.
[^2]: 리액트 팀원이 개발한 Flux 아키텍쳐의 구현체.
```

저는 이런 방식으로 작성하는게 좋을 것 같습니다~

2018-05-06 06:19 UTC, yangroro approved these changes

2018-05-21 04:01 UTC, merged